### ISSUE TITLE
Suggested development environment doesn't work on MacOS

### ISSUE THREAD

**Issue by imtixz** [jonogon/jonogon-mono#1]
> Cannot find module @rollup/rollup-linux-arm64-gnu. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.

An OS specific dependency is installed when running `pnpm install` and causes this error when running the docker compose file, which is expecting the linux version. But running the installation inside docker container solves the problem. Can we change the suggested `pnpm install` command to 

`docker compose run --entrypoint "sh -c 'pnpm install'" mono`

This runs the pnpm install command inside the docker container and makes it more OS-agnostic and reduces dependencies as well since the host machine doesn't even need the same node version or pnpm installed anymore

**Comment by omranjamal** [comment]
Yes!
