### ISSUE TITLE
Seeing Suggested Petition Modal every time I  vote, is annoying 

### ISSUE THREAD

**Issue by shahnewaz-labib** [jonogon/jonogon-mono#125]
We could display it randomly a certain percentage of the time to avoid being too intrusive.

![image](https://github.com/user-attachments/assets/249b08ee-a6f0-4322-904c-c8a2dfc9b2ed)

**Comment by hattima-tim** [comment]
@shahnewaz-labib Can I take the issue?

**Comment by shahnewaz-labib** [comment]
@hattima-tim go ahead

**Comment by hattima-tim** [comment]
@shahnewaz-labib Thanks vai .  I understand that I have to show the dabis randomly but I am having confusion regarding this line `certain percentage of the time`. Can you explain more please? Also how can I add dabis in the timeline? Currently whatever dabi I create goes into `My petitions` page, but can not see any in the timeline.

**Comment by hattima-tim** [comment]
@shahnewaz-labib Bro sorry about this, but it seems like this is not the standard procedure for contributing to the repo. It looks like I need to be first accepted to the team, since they are giving a google form to fill out and everything.  Hence I am dropping the task.

**Comment by shahnewaz-labib** [comment]
@hattima-tim you don't need to be in the team. Fork the repo, make changes to that fork and create a PR?
