### ISSUE TITLE
Dropdown or autocomplete text fields

### ISSUE THREAD

**Issue by Propo41** [jonogon/jonogon-mono#22]
![Screenshot_20240818-084315.png](https://github.com/user-attachments/assets/be40d98a-d624-43da-a014-6815fc8a7296)

The "who are you petitioning to" and "area" fields could be a drop down or an auto complete text field.

**Comment by omranjamal** [comment]
We surely want to keep it free-form input; how about we show suggestions when typing bu allow people to type anything they want?

**Comment by Propo41** [comment]
yes, in that case, an autocomplete text field can be used.

**Comment by omranjamal** [comment]
Are you intereted in tackling this issue and sending us a PR? @Propo41

**Comment by Propo41** [comment]
@omranjamal yes, I'll give a PR asap

**Comment by omranjamal** [comment]
Thanks. Keeping it assigned to you then.

**Comment by Propo41** [comment]
@omranjamal we need to store some hardcoded values and/or store the ones that the users enter. Where do we save them? Database (would have to create a lookup table) or directly in the frontend for now? What do you prefer?

**Comment by omranjamal** [comment]
I think directly in the frontend for now, we'll figure out how to store it in a DB later.
