### ISSUE TITLE
When I post a dabi, default should not count 1 disagree

### ISSUE THREAD

**Issue by aamaruf** [jonogon/jonogon-mono#24]
![image](https://github.com/user-attachments/assets/0160161f-6fff-4096-a2b0-dd51cf0af1ca)

1 count for agree is ok but 1 disagree count shouldn't be there

**Comment by omranjamal** [comment]
I fully agree. Fixed in commit [`36e4fa952fa547e3aefceb6a5f30f673d3b3177a`](https://github.com/jonogon/jonogon-mono/commit/36e4fa952fa547e3aefceb6a5f30f673d3b3177a)
