### ISSUE TITLE
add images in the preview of the "dabi" card

### ISSUE THREAD

**Issue by zulker0010** [jonogon/jonogon-mono#26]
Context: The "dabi" cards currently show the user's name, posted time the title of the "dabi" and the number of votes. To pinpoint the other users about what problem the petition is addressing, The first image of the uploaded media can be used as a default preview image of the "dabi".

Existing "dabi" card preview
Desktop:
![image 7](https://github.com/user-attachments/assets/8307df6c-c6a7-4fa9-915e-bc667fc9a8cc)
Mobile: 
![image 9](https://github.com/user-attachments/assets/d24cea4a-3b70-4aaa-ab6d-5b9916bc4693)

Suggested enhancement for the "dabi" card UI
Desktop:
![Screenshot 2024-08-18 184108](https://github.com/user-attachments/assets/7d2b6f08-f73f-4eae-a36d-7153120d6829)
Mobile: 
![mobile](https://github.com/user-attachments/assets/b841e0da-4c31-4e29-98d1-82375230bab2)

**Comment by omranjamal** [comment]
This is a splendid idea, are you interested in tackling this issue?
