### ISSUE TITLE
Not Receiving OTP for login

### ISSUE THREAD

**Issue by rifatud1** [jonogon/jonogon-mono#27]
Login OTP not working, I tried with different contact number(GP and Teletalk) and different devices(laptop, smartphone).
Possible Issue: out of balance, check the OTP service provider

**Comment by 0xriyadh** [comment]
Facing the same issue with "robi"

**Comment by aamaruf** [comment]
Most probably it was because the insufficient funds in SMS gateway 
It's working now

**Comment by imtixz** [comment]
seems like the issue has been solved. im closing this one
