### ISSUE TITLE
Need to Add Support for Soft Deleting of Petitions & Petition Votes

### ISSUE THREAD

**Issue by omranjamal** [jonogon/jonogon-mono#3]
Don't want to lose removed petitions forever.

**Comment by 0xriyadh** [comment]
@omranjamal I would like to take on the issue. I had some questions:
1. After deletion will the user be able to see the petition in trash or archive it or will it only be accessible by the mods?
2. Is it possible to re-publish the petition again?
3. Will the votes remain as it is or be removed?

**Comment by omranjamal** [comment]
Hey @0xriyadh, I would love to assign this to you.

1. The users will not be able to see the petitions anymore.
2. No
3. Yes the votes should infact remain.

DM me on Discord if you have any other confusions.

**Comment by 0xriyadh** [comment]
> Hey @0xriyadh, I would love to assign this to you.
> 
> 
> 
> 1. The users will not be able to see the petitions anymore.
> 
> 2. No
> 
> 3. Yes the votes should infact remain.
> 
> 
> 
> DM me on Discord if you have any other confusions.

Thank you @omranjamal, I will start working asap...
