### ISSUE TITLE
Auto Update not working in Docker

### ISSUE THREAD

**Issue by RayZ3R0** [jonogon/jonogon-mono#30]
I do not really know much about dockers as I have not used them before, but I got it running with the Quick Start guide in the ReadMe and the website works fine, but HMR is not working for me, I tried changing some code but there was no change in the website. Like for example I changed the text Jonogoner Dabi to ABCD here in the screenshot but there was no change.

OS: Windows 11
Docker Compose version v2.28.1-desktop.1

![image](https://github.com/user-attachments/assets/269440af-d0fb-4d04-94da-1943ab7e0ef8)
![image](https://github.com/user-attachments/assets/43cc6cef-a376-41c0-a4df-81685703f259)

**Comment by aamaruf** [comment]
I think it's working fine.
For example try again by changing -> 'Your Own দাবিs'

You couldn't see the change because the condition was not going to else block

**Comment by omranjamal** [comment]
Hi, could you solve your issue?

**Comment by RayZ3R0** [comment]
> I think it's working fine. For example try again by changing -> 'Your Own দাবিs'
> 
> You couldn't see the change because the condition was not going to else block


No, I also tried changing that, no change as well. I tried changing other text in the code, same problem. Console shows watching for file changes but there is no update in console either

**Comment by omranjamal** [comment]
Are you on Windows? If so, is your repo in your windows managed drive or is it inside WSL?

**Comment by RayZ3R0** [comment]
> Are you on Windows? If so, is your repo in your windows managed drive or is it inside WSL?

Uh, I don't know about that. I git cloned the repo in a folder and ran the quick start guide inside the cloned folder

**Comment by RayZ3R0** [comment]
hello?

**Comment by omranjamal** [comment]
It's harder to assist you when you don't know the exact parameters of starting your system. Can you help us know the answers to the above question?

**Comment by omranjamal** [comment]
1. Are you running docker inside WSL?
2. Did you run git clone inside WSL or on your Windows system?
3. What filesystem is your cloned project on?

**Comment by RayZ3R0** [comment]
Ohh I had to run this in WSL? I did it on my terminal on windows. Cloned it on windows filesystem. Sorry I'll look into how to use WSL and try again. It wasn't written in the guide that I had to use WSL though

**Comment by omranjamal** [comment]
No I'm not saying you had to do that, we don't really know but knowing this gives us more infomration to work with to resolve your issue. Having said that, most of the cor econtributors team is on a Linux and some are on a MacOS hence we couldn't test the development workflow on a Windows.

Would you be open to seding a PR for the documentation with instructions once you get it working with Windows?

**Comment by RayZ3R0** [comment]
Aight sure, if I can get it working. Or I might just boot up linux and try there if I can't.

**Comment by RayZ3R0** [comment]
Ok I got it working with WSL, its now auto updating

**Comment by 0xriyadh** [comment]
> Ok I got it working with WSL, its now auto updating

@RayZ3R0 can you please submit a PR updating the [README.md](https://github.com/jonogon/jonogon-mono/blob/main/README.md) file on how you solved the issue?

Other people seems to be having similar issues #57

**Comment by omranjamal** [comment]
That was beautifully done bro! Thank you so much!
