### ISSUE TITLE
change the favicon & fix spelling

### ISSUE THREAD

**Issue by aamaruf** [jonogon/jonogon-mono#32]
Favicon showing -> nextjs logo
![image](https://github.com/user-attachments/assets/6372e574-c3a0-4a53-9bc2-3dad4a6179ac)

Fix the spelling কোন not কন 
![Screenshot from 2024-08-20 21-58-46](https://github.com/user-attachments/assets/612be94e-4602-46e9-bd60-c063a1a0d193)

**Comment by omranjamal** [comment]
Would love to recieve a PR for the second point. I'm already working on the favicon.

**Comment by omranjamal** [comment]
Comment back here if you're working on it.

**Comment by aamaruf** [comment]
I'm still struggling with the code prettier
