### ISSUE TITLE
Users should be able to see the "Vote Bar" even when logged out

### ISSUE THREAD

**Issue by omranjamal** [jonogon/jonogon-mono#33]
![image](https://github.com/user-attachments/assets/dc9e142a-729e-4f7f-bae3-f0fd0ac409a3)

1. The vote bar typically seen on the bottom of the petition page should be visible even when logged out.
2. The bar shold show the votes as usual.
3. The buttons should take the user to the login page on press if the user is logged out.
4. The appropriate `?next=[URL]` should be set where `[URL]` is the url of the current petition.

**Comment by shawonibnkamal** [comment]
I can take this

**Comment by omranjamal** [comment]
Assigned!

**Comment by shawonibnkamal** [comment]
Not being able to tag reviewers but here's the PR - https://github.com/jonogon/jonogon-mono/pull/42
