### ISSUE TITLE
Add loading screens?

### ISSUE THREAD

**Issue by imtixz** [jonogon/jonogon-mono#47]
When a petition page is opened, it briefly shows default values like Untitled Petition. On the home page, it briefly shows an empty list. This can be confusing, specially for someone with a bad internet speed. Probably should show a loading screen when data is being fetched in both of these screens. Not sure what the loading screen should look like tho.

**Comment by omranjamal** [comment]
Yes pls. You wanna?

**Comment by imtixz** [comment]
not right now, no. wanted to start the conversation so someone takes it up

**Comment by omranjamal** [comment]
okay.

**Comment by omranjamal** [comment]
Done.
