### ISSUE TITLE
keep all the image contained in fixed size

### ISSUE THREAD

**Issue by aamaruf** [jonogon/jonogon-mono#50]
images are being uploaded in different sizes, which making the view shattered
keep the image area fixed, no matter the size the image should in a fixed barrier 
![image](https://github.com/user-attachments/assets/1eae2f5a-c184-46c7-b5ad-b2c40e7b54d9)

**Comment by omranjamal** [comment]
Sounds like a good idea, could you give us a PR?

**Comment by aamaruf** [comment]
![Screenshot from 2024-08-23 23-42-25](https://github.com/user-attachments/assets/335245d9-1752-42aa-815a-bd6e457f17ef)

It looks better now
