### ISSUE TITLE
Auto update is not working in docker.

### ISSUE THREAD

**Issue by KaziAbdurRahim** [jonogon/jonogon-mono#57]
### Description

I tried to test by changing the 'Your Own দাবিs' with 'দাবিs', but it is not working.
![image](https://github.com/user-attachments/assets/3d2f4a40-f003-4870-a5a7-d0fa47ed2a8c)
 I looked into issue [#30](https://github.com/jonogon/jonogon-mono/issues/30), but it didn't help.

### Process Taken

1. **Clone Path**:  C:\Devprojects>git clone https://github.com/KaziAbdurRahim/jonogon-mono.git
![image](https://github.com/user-attachments/assets/0fc65ea2-beca-4ec9-8721-6e8ace05001e)
2. **Command Execution**: Ran the command as mentioned.
3. **Issue**: The file opens, but any code changes don't reflect on the web app.

### Device and Setup

1. **Device**:
   - **Processor**: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz 2.30 GHz
   - **RAM**: 16.0 GB (15.7 GB usable)
   - **System Type**: 64-bit operating system, x64-based processor
2. **Operating System**: Windows 11, version 23H2
3. **Docker**: Running in WSL 2

![Screenshot 2024-08-24 074231](https://github.com/user-attachments/assets/0ecb3e55-9002-49c6-ad7a-588846b40c93)
![Screenshot 2024-08-24 074334](https://github.com/user-attachments/assets/c421af83-bcee-4f5b-bbc5-0b6d4184f094)

**Comment by KaziAbdurRahim** [comment]
And i think my docker is running in WSL 

![image](https://github.com/user-attachments/assets/86b32bca-1a15-4420-b1fd-4dedd8828843)

![image](https://github.com/user-attachments/assets/e0e6ce86-c0eb-412e-80dd-17e89c036e13)

**Comment by omranjamal** [comment]
Deplicate of #30
