### ISSUE TITLE
/login should redirect to / if I'm already logged in

### ISSUE THREAD

**Issue by shahnewaz-labib** [jonogon/jonogon-mono#59]
Here, I'm logged in and still can request for OTPs.

![image](https://github.com/user-attachments/assets/99896d71-597e-4f1b-b900-93e411cf62a6)

**Comment by omranjamal** [comment]
PR hoye jaak bros?

**Comment by dewantawsif** [comment]
Looking into this

**Comment by shahnewaz-labib** [comment]
@dewantawsif bro any progress on this?
